Rchriste/backport dfl cxl cache ao
OPAE/linux-dfl-backport pull request #107
Opened 2024-01-22 17:34 UTC by rchriste1

The previously added files dfl-cxl-cache.c, dfl-priv-feat-main.c, and dfl-platform.c does not compile on CentOS 8.2 (kernel 4.18.0-193.el8.x86_64) and CentOS 8.3 (kernel 4.18.0-240.22.1.el8_3.x86_64).

These files are backported.

Also backport of dev_err_probe() is simplified.

2024-01-22 20:46 UTC, pcolberg requested changes
Thanks @rchriste1! The corresponding CI tests have been added in https://github.com/OFS/linux-dfl-backport/pull/109.

Nit on commit messages: For some reason the bodies are indented by an extra tab.

2024-01-22 20:46 UTC, pcolberg commented on include/linux/dfl.h
> +
Could you add a comment referencing the original commit which introduced the function? I believe it is `a787e5400a1c ("driver core: add device probe log helper")`.

2024-01-22 20:46 UTC, pcolberg commented on include/linux/dfl.h
> +#endif
We try to keep the DFL-specific files as close as possible to the latest linux-dfl -lts branch, hence I would suggest moving this to the header in which it is defined upstream. The declaration was recently moved to `include/linux/dev_printk.h`, but it may be better to have it in the original location `include/linux/device.h` if the former header is not present in older kernels (which I did not check).

2024-01-22 20:46 UTC, pcolberg commented on include/linux/dfl.h
> +	return 0;
```suggestion
	return err;
```

2024-01-22 20:46 UTC, pcolberg commented on drivers/net/phy/qsfp-mem-platform.c
> +#include <linux/dfl.h>
This should be dropped once `dev_err_probe` is moved to upstream header.

2024-01-22 20:46 UTC, pcolberg commented on drivers/fpga/dfl-cxl-cache.c
> +#endif
Can this be moved to a common header, to reuse in `dfl-afu-dma-region.c`?

2024-01-22 20:46 UTC, pcolberg commented on drivers/fpga/dfl-platform.c
> +#include <linux/dfl.h>
Why is this needed?

2024-01-22 20:51 UTC, pcolberg commented on drivers/fpga/dfl-platform.c
> +#include <linux/dfl.h>
Please never mind, same reason as https://github.com/OFS/linux-dfl-backport/pull/107#discussion_r1462387020; `dfl-platform` driver was added recently in commit 6a5e47cf83a2900482554a14d238f8d648a17645.

2024-01-23 08:22 UTC, rchriste1 commented on include/linux/dfl.h
> +
Yes

2024-01-23 08:22 UTC, rchriste1 commented on include/linux/dfl.h
> +#endif
Good point. I will move it to include/linux/device.h.

2024-01-23 08:23 UTC, rchriste1 commented on include/linux/dfl.h
> +	return 0;
Good spotted.

2024-01-23 08:24 UTC, rchriste1 commented on drivers/fpga/dfl-cxl-cache.c
> +#endif
Yes. I should have done that in the first place.

2024-01-23 08:25 UTC, rchriste1 commented on drivers/net/phy/qsfp-mem-platform.c
> +#include <linux/dfl.h>
Yes.

2024-01-23 08:26 UTC, rchriste1 commented on drivers/fpga/dfl-platform.c
> +#include <linux/dfl.h>
Removed.

2024-01-23 20:39 UTC, pcolberg commented on include/linux/device.h
> +	dev_err(dev, fmt);
Apologies for missing this in the first round, but this does not forward the variable arguments. How about this simplified variant of the [upstream function](https://elixir.bootlin.com/linux/latest/source/drivers/base/core.c#L4955), without `device_set_deferred_probe_reason()` which is absent on the CentOS kernels?
```suggestion
	struct va_format vaf;
	va_list args;

	va_start(args, fmt);
	vaf.fmt = fmt;
	vaf.va = &args;
	dev_err(dev, "error %pe: %pV", ERR_PTR(err), &vaf);
	va_end(args);
```

2024-01-24 08:10 UTC, rchriste1 commented on include/linux/device.h
> +	dev_err(dev, fmt);
Thanks, yes that's the way to handle variable arguments. I didn't pay enough attention. It is good to keep it close to the upstream function. I will update the commit with this change.

2024-01-24 08:27 UTC, rchriste1 commented on include/linux/device.h
> +	dev_err(dev, fmt);
I can actually use the original function from commit a787e5400a1c, that also handles -EPROBE_DEFER.

2024-01-25 00:38 UTC, pcolberg approved these changes

2024-01-25 00:38 UTC, merged