Intel test/fpga ofs dev 6.1 lts/SRIOV cleanup patches and sync to dev branch
OPAE/linux-dfl-backport pull request #84
Opened 2023-06-30 10:47 UTC by Muralix

2023-06-30 16:35 UTC, rweight approved these changes
Looks good to me

2023-07-03 05:42 UTC, rchriste1 requested changes

2023-07-03 05:42 UTC, rchriste1 commented on drivers/fpga/dfl-fme-main.c
> +		*val = (long)(FIELD_GET(FPGA_TEMPERATURE, v) * MILLI);
MILLI is not known on RHEL 8.5 and 8.8:
linux-dfl-backport/drivers/fpga/dfl-fme-main.c:257:50: error: ‘MILLI’ undeclared (first use in this function)
   *val = (long)(FIELD_GET(FPGA_TEMPERATURE, v) * MILLI);
                                                  ^~~~~
It compiles and runs on Ubuntu 22.04

2023-07-03 11:55 UTC, Muralix commented on drivers/fpga/dfl-fme-main.c
> +		*val = (long)(FIELD_GET(FPGA_TEMPERATURE, v) * MILLI);
defined macro MILLIO in units.h. Compiled on RHEL 8.2.

2023-07-05 11:47 UTC, merged

2023-07-07 00:12 UTC, rweight commented
This was merged as a merge-commit instead of a rebase (fast-forward) merge. This was permitted because the rules were never set up properly for this branch. I have fixed the branch-rules and  I have force-pushed over the top to restore a linear history. The code is functionally unchanged. I did, however, split out the units.h changes into a separate backport commit and I changed some spaces to tabs in the units.h file.